# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:          # List of stages for jobs, and their order of execution
  - release


release_ci:
  stage: release
  when: manual
  tags:
    - release
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - ${CI_COMMIT_BRANCH}-${CI_COMMIT_TAG}.tar.bz2
  script:
    - scripts/release.sh
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
    name: "${CI_COMMIT_TAG}-release"
    assets:
      links:
        - name: "${CI_COMMIT_BRANCH}-${CI_COMMIT_TAG}.tar.bz2"
          filepath: "/${CI_COMMIT_BRANCH}-${CI_COMMIT_TAG}.tar.bz2"
          url: "http://10.8.1.216:9000/embedded-sw/sdk/-/jobs/${CI_JOB_ID}/artifacts/raw/${CI_COMMIT_BRANCH}-${CI_COMMIT_TAG}.tar.bz2"
