# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_DR1M90) += anlogic-dr1m90-linux.dtb
dtb-$(CONFIG_ARCH_DR1M90) += anlogic-dr1m90-linux-openamp.dtb
dtb-$(CONFIG_ARCH_DR1M90) += anlogic-dr1m90-evb.dtb
dtb-$(CONFIG_ARCH_DR1M90) += anlogic-dr1m90-evb-usb_device.dtb
